def help():
    print("==================================================")
    print("         Bienvenue dans ctOS - CLI Tranquillity")
    print("==================================================\n")
    print("USAGE :")
    print("  ctOS [commande]")
    print("  ctOS [option]\n")
    print("COMMANDES PRINCIPALES :\n")
    print("  --start              Lance le programme principal Tranquillity")
    print("GESTION MUSICALE :\n")
    print("  --music pause        Met en pause la musique en cours")
    print("  --music resume       Reprend la musique en pause")
    print("  --music device       Affiche et gere les appareils audio connectes\n")
    print("CONTROLE DOMOTIQUE :\n")
    print("  --light toggle       Active/desactive les lumieres connectees\n")
    print("OUTILS ET CONFIGURATION :\n")
    print("  --init               Initialise le token Spotify et vérification")
    print("  --send [message]     Envoie un message via Discord\n")
    print("AUTRES :\n")
    print("  --help, -h           Affiche ce message d'aide\n")
    print("==================================================\n")